project:
  type: website
  output-dir: docs

format: 
  html: 
    theme: 
    - default
    - custom.scss
  
website:
  title: "Diego Catalan Molina's Portfolio"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "About"
        file: about.qmd