---
title: "About"
format: html
---

I started out as a school counselor in Chile, where I grew up. I was interested in contributing to schools and teachers, especially those in vulnerable neighborhoods who were strapped for resources. My training in Psychology and Education provided a great foundation to start my journey.

Soon enough, I realized I wanted to learn more to have a larger impact. I came to the US for graduate training, where I learned much about research, data, and evaluation. My main focus was to answer questions around how and under what conditions interventions work.

All these experiences built the skills I needed to take a leadership and mentoring role at a B2B SaaS company. They built my people-first skills, as well as my quant and qual skills. Most importantly, they helped me understand how to leverage research to make decisions.

## 🧠 Skills

**Research**: Mixed methods, UX research, survey design, RCTs, qualitative coding, and psychometrics. 

**Data Science Tools**: R, R Markdown, Quarto, GitHub, APIs, and MongoDB.

**Management & Ops**: Team leadership, project management, grant writing, OKRs, documentation systems, and stakeholder collaboration.

**Communication**: Report writing, data storytelling, cross-functional communication, and teaching & training.
