---
title: ""
format: html
---

# 👋 Hi there!

I am an experienced research leader with a PhD and a track record of building research operations from the ground up. I lead a bilingual, remote-first team at [Hello Insight](https://helloinsight.org), a B2B SaaS company, that turns messy data into clear insights.

## 📁 Public Projects

- [Core Ideas](https://github.com/dcatalanmolina/Core-Ideas): A free, introductory course to R. I created this course to help labmates in grad school and then I improved it to help others who were struggling to get started in R. Along the code, I wrote a series of Substack posts in English and Spanish (with videos) to help people learn.

- [Compañero](https://companero.substack.com): I had so much fun building Core Ideas that I kept writing on workflow and communication. For example, I wrote a step-by-step series on how to create [paged HTML documents in R](https://companero.substack.com/p/how-to-create-a-paged-html-document). 

- [Local AI Agents](https://github.com/dcatalanmolina/uxr-local-agents): Examples of reliable local AI agents using small language models via [Ollama](https://ollama.com/). Check out the experiments I've run to build privacy-first agents to solve real problems for ResearchOps and UX researchers.

- [Insights Vault](https://github.com/dcatalanmolina/insights-vault): Check out an awesome vault for your insights, built on top of Obsidian and a couple of their community plugins. We built this for free, aiming to keep our company insights private and modular as we scale up.

Do you want to learn more about my work? Check out my research [here](https://osf.io/ev3yn/).